#!/usr/bin/env python3
"""Generate the photo albums: the album cards on the Photography page and one page per album.

Usage (from the site root; the path is optional):
    python3 tools/build_albums.py [data/albums.json]

What it writes
- photography/index.html — the album cards between these markers, in JSON order:
      <!-- BEGIN:ALBUMS ... -->  ...  <!-- END:ALBUMS -->
- photography/<slug>/index.html for every album — the whole file. The page skeleton (head, site header with the
  menu, footer) is copied from photography/index.html at build time, so a menu or footer change made in the seven
  hand-written pages reaches the album pages on the next run. Only <title>, the description/social tags, the
  canonical URL and the menu's current-page marker differ.
- sitemap.xml — adds any album page that is not listed yet (with the Photography page's lastmod).

Every image file an album needs must exist (see tools/album_images.py); the script stops if one is missing.
No third-party packages needed.
"""
import json
import os
import re
import sys

sys.dont_write_bytecode = True   # importing the sibling script must not leave a __pycache__ folder in the site
from build_publications import esc, replace_block

SITE = "https://pinakibhaskar.github.io"
ALBUM_DIR = "/assets/albums"
MAIN_OPEN = '<main id="main" tabindex="-1">'
MAIN_CLOSE = "    </main>"


def tile_html(slug, photo, indent="    "):
    stem = f'{ALBUM_DIR}/{slug}/{photo["id"]}'
    full = photo["full"]
    out = [
        '<li><figure class="photo">',
        f'  <a href="{stem}-full.jpg" data-w="{full["w"]}" data-h="{full["h"]}"><picture>'
        f'<source type="image/webp" srcset="{stem}-480.webp">'
        f'<img src="{stem}-480.jpg" width="480" height="360" alt="{esc(photo["alt"])}" '
        'loading="lazy" decoding="async"></picture></a>',
        f'  <figcaption>{esc(photo["title"])}</figcaption>',
        '</figure></li>',
    ]
    return "\n".join(indent + line for line in out)


def cover_of(album):
    for p in album["photos"]:
        if p["id"] == album["cover"]:
            return p
    sys.exit(f'ERROR: album "{album["slug"]}": cover {album["cover"]!r} is not one of its photos')


def facts(album, sep=' <span class="dot" aria-hidden="true">·</span> '):
    """'107 photographs · September – November 2011' (the date part only when known; `sep` joins the two)."""
    n = len(album["photos"])
    out = f"{n} photograph{'s' if n != 1 else ''}"
    if album.get("when"):
        out += sep + esc(album["when"])
    return out


def card_html(album):
    slug, cover = album["slug"], cover_of(album)
    stem = f'{ALBUM_DIR}/{slug}/{cover["id"]}'
    return "\n".join([
        '    <li class="card">',
        '      <picture class="card__media plate">',
        f'        <source type="image/webp" srcset="{stem}-full.webp">',
        f'        <img src="{stem}-full.jpg" width="{cover["full"]["w"]}" height="{cover["full"]["h"]}" loading="lazy" decoding="async"',
        f'             alt="{esc(cover["alt"])}">',
        '      </picture>',
        f'      <h3 class="card__title" id="album-{esc(slug)}-title">{esc(album["title"])}</h3>',
        f'      <p class="card__hook">{esc(album["card_line"])}</p>',
        f'      <p class="card__text">{facts(album)}</p>',
        f'      <a class="card__link" href="/photography/{esc(slug)}/" aria-labelledby="album-{esc(slug)}-title">Open the album<span aria-hidden="true"> →</span></a>',
        '    </li>',
    ])


def set_meta(head, attr, key, value):
    pattern = re.compile(rf'(<meta {attr}="{re.escape(key)}" content=")[^"]*(")')
    if len(pattern.findall(head)) != 1:
        sys.exit(f'ERROR: expected exactly one <meta {attr}="{key}"> in photography/index.html')
    return pattern.sub(lambda m: m.group(1) + esc(value) + m.group(2), head, count=1)


def album_body(album, prev_album, next_album):
    slug = album["slug"]
    n = len(album["photos"])
    tiles = "\n".join(tile_html(slug, p) for p in album["photos"])
    links = []
    if prev_album:
        links.append(f'      <li><a class="btn btn--secondary btn--small" href="/photography/{esc(prev_album["slug"])}/">'
                     f'<svg width="16" height="16" aria-hidden="true" focusable="false"><use href="#i-prev"/></svg>{esc(prev_album["title"])}</a></li>')
    links.append('      <li><a class="btn btn--secondary btn--small" href="/photography/#albums">All albums</a></li>')
    if next_album:
        links.append(f'      <li><a class="btn btn--secondary btn--small" href="/photography/{esc(next_album["slug"])}/">'
                     f'{esc(next_album["title"])}<svg width="16" height="16" aria-hidden="true" focusable="false"><use href="#i-next"/></svg></a></li>')
    return f"""
<!-- Generated by tools/build_albums.py from data/albums.json — edit the JSON and run the script, not this file. -->
<section class="section section--first" id="album" aria-labelledby="album-title">
  <header class="section__head row" data-reveal>
    <p class="crumbs"><a href="/photography/">Photography</a><span aria-hidden="true"> / </span><a href="/photography/#albums">Albums</a></p>
    <h1 class="section__title" id="album-title">{esc(album["title"])}</h1>
  </header>

  <div class="row" data-reveal>
    <p class="photos__label">{facts(album, "<br>")}</p>
    <p>{esc(album["intro"])}</p>
  </div>

  <ul class="photos" data-lightbox="{esc(album["title"])}" data-reveal>
{tiles}
  </ul>

  <nav class="album-nav row" aria-label="Other albums">
    <p class="photos__label" aria-hidden="true">More albums</p>
    <ul>
{chr(10).join(links)}
    </ul>
  </nav>
</section>
"""


def album_page(skeleton, album, prev_album, next_album):
    head, tail = skeleton
    slug, cover = album["slug"], cover_of(album)
    n = len(album["photos"])
    title = f'{album["title"]} — Photography — Dr. Pinaki Bhaskar'
    desc = album.get("description") or f'{album["card_line"]}. {n} photographs by Pinaki Bhaskar.'
    url = f"{SITE}/photography/{slug}/"
    og = f"{SITE}{ALBUM_DIR}/{slug}/og.jpg"
    head = re.sub(r"<title>.*?</title>", f"<title>{esc(title)}</title>", head, count=1)
    head = set_meta(head, "name", "description", desc)
    head, k = re.subn(r'(<link rel="canonical" href=")[^"]*(")', rf"\g<1>{url}\2", head)
    if k != 1:
        sys.exit("ERROR: canonical link not found in photography/index.html")
    for key, val in [("og:title", title), ("og:description", desc), ("og:url", url), ("og:image", og),
                     ("og:image:width", str(album["og"]["w"])), ("og:image:height", str(album["og"]["h"])), ("og:image:alt", cover["alt"])]:
        head = set_meta(head, "property", key, val)
    for key, val in [("twitter:title", title), ("twitter:description", desc), ("twitter:image", og), ("twitter:image:alt", cover["alt"])]:
        head = set_meta(head, "name", key, val)
    current = '<a href="/photography/" aria-current="page">Photography</a>'
    if head.count(current) != 1:
        sys.exit("ERROR: the Photography menu entry was not found in photography/index.html")
    head = head.replace(current, '<a href="/photography/" aria-current="true">Photography</a>')
    return head + album_body(album, prev_album, next_album) + "\n" + tail


def check_files(root, albums):
    missing = []
    for a in albums:
        for p in a["photos"]:
            for suffix in ("-480.webp", "-480.jpg", "-full.webp", "-full.jpg"):
                rel = f'{ALBUM_DIR}/{a["slug"]}/{p["id"]}{suffix}'
                if not os.path.exists(os.path.join(root, rel.lstrip("/"))):
                    missing.append(rel)
        if not os.path.exists(os.path.join(root, ALBUM_DIR.lstrip("/"), a["slug"], "og.jpg")):
            missing.append(f'{ALBUM_DIR}/{a["slug"]}/og.jpg')
        ids = [p["id"] for p in a["photos"]]
        if len(set(ids)) != len(ids):
            sys.exit(f'ERROR: album "{a["slug"]}" has duplicate photo ids')
        for p in a["photos"]:
            if not p.get("alt") or not p.get("title"):
                sys.exit(f'ERROR: album "{a["slug"]}", photo {p["id"]}: "title" and "alt" must both be filled in')
    if missing:
        sys.exit("ERROR: missing image files:\n  " + "\n  ".join(missing))


def update_sitemap(root, albums, photo_page_path):
    path = os.path.join(root, "sitemap.xml")
    with open(path, encoding="utf-8") as fh:
        xml = fh.read()
    m = re.search(r"<loc>https://pinakibhaskar.github.io/photography/</loc>\s*<lastmod>([^<]+)</lastmod>", xml)
    lastmod = m.group(1) if m else "2026-10-07"
    added = []
    for a in albums:
        loc = f'{SITE}/photography/{a["slug"]}/'
        if f"<loc>{loc}</loc>" not in xml:
            entry = f"  <url>\n    <loc>{loc}</loc>\n    <lastmod>{lastmod}</lastmod>\n  </url>\n"
            xml = xml.replace("</urlset>", entry + "</urlset>")
            added.append(loc)
    if added:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(xml)
    return added


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.normpath(os.path.join(here, ".."))
    data_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(root, "data", "albums.json")
    photo_page = os.path.join(root, "photography", "index.html")
    with open(data_path, encoding="utf-8") as fh:
        albums = json.load(fh)["albums"]
    check_files(root, albums)

    # 1. The cards on the Photography page
    with open(photo_page, encoding="utf-8") as fh:
        page = fh.read()
    page = replace_block(page, "ALBUMS", "\n".join(card_html(a) for a in albums))
    with open(photo_page, "w", encoding="utf-8") as fh:
        fh.write(page)

    # 2. One page per album, built on the Photography page's skeleton (as just written)
    if page.count(MAIN_OPEN) != 1 or page.count(MAIN_CLOSE) != 1:
        sys.exit("ERROR: could not find the <main> boundaries in photography/index.html")
    head = page[: page.index(MAIN_OPEN) + len(MAIN_OPEN)] + "\n"
    tail = page[page.index(MAIN_CLOSE):]
    for i, a in enumerate(albums):
        prev_album = albums[i - 1] if i > 0 else None
        next_album = albums[i + 1] if i + 1 < len(albums) else None
        out_dir = os.path.join(root, "photography", a["slug"])
        os.makedirs(out_dir, exist_ok=True)
        with open(os.path.join(out_dir, "index.html"), "w", encoding="utf-8") as fh:
            fh.write(album_page((head, tail), a, prev_album, next_album))
        print(f'Wrote photography/{a["slug"]}/index.html ({len(a["photos"])} photographs)')

    added = update_sitemap(root, albums, photo_page)
    for loc in added:
        print(f"Added to sitemap.xml: {loc}")
    print(f"Wrote {len(albums)} album cards to photography/index.html")


if __name__ == "__main__":
    main()
